### ISSUE TITLE
urn:acme:error:m alformed: Unable to update challenge :: provided key authorization was incorrect

### ISSUE THREAD

**Issue by appqui** [ridercz/AutoACME#27]
Any ideas, what I am doing wrong?

```
C:\CertStore\AutoACME>autoacme addhost firm24.com.ua /verbose
Altairis AutoACME Manager version 1.5.4.0
Copyright (c) Michal A. Valasek - Altairis, 2017
www.autoacme.net | www.rider.cz | www.altairis.cz

Reading configuration from 'C:\CertStore\AutoACME\autoacme.json'...OK
Checking host...OK
Requesting cerificate for firm24.com.ua:
  Accepting TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017
.pdf...OK
  Testing authorization:
    Writing challenge to C:\InetPub\wwwroot\AutoAcme\probe_b4299cc5-3271-4ede-b6
02-2fb7a0fe4d91...OK
    Testing HTTP challenge:
      Preparing request to http://firm24.com.ua/.well-known/acme-challenge/probe
_b4299cc5-3271-4ede-b602-2fb7a0fe4d91...OK
      Getting response...OK
      Reading response...OK
        OK: Status code 200
        OK: Content-Type header
        OK: Expected response received
    Deleting challenge from C:\InetPub\wwwroot\AutoAcme\probe_b4299cc5-3271-4ede
-b602-2fb7a0fe4d91...OK
  Getting authorization:
    Creating authorization request...OK, the following is request URI:
    https://acme-v01.api.letsencrypt.org/acme/authz/SzckWN9xnv71stH3FCzo4SUTNjgV
KT0lv2g1jadwx5I
    Getting challenge...OK, the following is challenge URI:
    https://acme-v01.api.letsencrypt.org/acme/challenge/SzckWN9xnv71stH3FCzo4SUT
NjgVKT0lv2g1jadwx5I/5387278631
    Writing challenge to C:\InetPub\wwwroot\AutoAcme\9p0CMVPAOZC47JXZYK_CyUN6K1H
orKdvVqgngoCgqXk...OK
    Completing challenge...Request failed: One or more errors occurred.


    System.AggregateException: One or more errors occurred. ---> System.Aggregat
eException: One or more errors occurred. ---> System.Exception: urn:acme:error:m
alformed: Unable to update challenge :: provided key authorization was incorrect
 (BadRequest)
   at Certes.AcmeClient.ThrowIfError[T](AcmeResponse`1 response)
   at Certes.AcmeClient.<CompleteChallenge>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Altairis.AutoAcme.Core.AcmeContext.<GetAuthorization>d__18.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotifica
tion)
   at System.Threading.Tasks.Task`1.get_Result()
   at Altairis.AutoAcme.Core.AcmeContext.<GetCertificateAsync>d__14.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotifica
tion)
   at System.Threading.Tasks.Task`1.get_Result()
   at Altairis.AutoAcme.Core.AcmeContext.GetCertificate(String hostName, String
pfxPassword, Action`2 challengeCallback, Action`1 cleanupCallback, Boolean skipT
est)
   at Altairis.AutoAcme.Manager.Program.AddHost(String hostName, Boolean skipTes
t, String cfgFileName, Boolean verbose)
---> (Inner Exception #0) System.AggregateException: One or more errors occurred
. ---> System.Exception: urn:acme:error:malformed: Unable to update challenge ::
 provided key authorization was incorrect (BadRequest)
   at Certes.AcmeClient.ThrowIfError[T](AcmeResponse`1 response)
   at Certes.AcmeClient.<CompleteChallenge>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Altairis.AutoAcme.Core.AcmeContext.<GetAuthorization>d__18.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotifica
tion)
   at System.Threading.Tasks.Task`1.get_Result()
   at Altairis.AutoAcme.Core.AcmeContext.<GetCertificateAsync>d__14.MoveNext()
---> (Inner Exception #0) System.Exception: urn:acme:error:malformed: Unable to
update challenge :: provided key authorization was incorrect (BadRequest)
   at Certes.AcmeClient.ThrowIfError[T](AcmeResponse`1 response)
   at Certes.AcmeClient.<CompleteChallenge>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Altairis.AutoAcme.Core.AcmeContext.<GetAuthorization>d__18.MoveNext()<---
<---

    Failed!
    Unable to get certificate for new host.
```

**Comment by ridercz** [comment]
Looks like something is in between LE verification servers and your server that modifies the response. Looks more like environment issue than AutoACME bug.
