### ISSUE TITLE
Request failed when adding a new host

### ISSUE THREAD

**Issue by matt-01** [ridercz/AutoACME#29]
I have encountered a problem trying to add a new host to the server in which it seems to be getting stuck right at the end:

```
Requesting cerificate for example.com:
  Accepting TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf...OK
  Testing authorization:
    Writing challenge to C:\Websites\AutoACME\autoACME\probe_2426f445-ac5a-43bc-8418-8564eec9d001...OK
    Testing HTTP challenge:
      Preparing request to http://example.com/.well-known/acme-challenge/probe_2426f445-ac5a-43bc-8418-8564eec9d001...OK
      Getting response...OK
      Reading response...OK
        OK: Status code 200
        OK: Content-Type header
        OK: Expected response received
    Deleting challenge from C:\Websites\AutoACME\autoACME\probe_2426f445-ac5a-43bc-8418-8564eec9d001...OK
  Getting authorization:
    Creating authorization request...OK, the following is request URI:
    https://acme-v01.api.letsencrypt.org/acme/authz/qtW814qPGbfyWnSB5-S3A3xafPRX_JBkM57nzky7KW0
    Getting challenge...OK, the following is challenge URI:
    https://acme-v01.api.letsencrypt.org/acme/challenge/qtW814qPGbfyWnSB5-S3A3xafPRX_JBkM57nzky7KW0/7897219451
    Writing challenge to C:\Websites\AutoACME\autoACME\FY_TrYtokAhf1kfzasVpiSA6N1yd6yDyYrceGkqRGow...OK
    Completing challenge...OK
    Waiting for authorization...OK
    Deleting challenge from C:\Websites\AutoACME\autoACME\FY_TrYtokAhf1kfzasVpiSA6N1yd6yDyYrceGkqRGow...OK
  Processing certificate:
    Requesting certificate...Request failed: One or more errors occurred.
    Failed!
    Unable to get certificate for new host.
```

Everything seems to be working and when I go to http://example/com/.well-known/acme-challenge/  likewise http://localhost/.well-known/acme-challenge/ also works just fine on the server.

But it seems to be stuck at the point it is requesting the certificate, any ideas?

**Comment by matt-01** [comment]
I would also like to add that I was having trouble renewing the certificate so I deleted it by running autoacme.exe delhost example.com

**Comment by ridercz** [comment]
Please run the command with `--verbose` argument. It will give you detailed error message.

**Comment by matt-01** [comment]
```
Altairis AutoACME Manager version 1.5.4.0
Copyright (c) Michal A. Valasek - Altairis, 2017
www.autoacme.net | www.rider.cz | www.altairis.cz

Reading configuration from 'C:\CertStore\AutoACME\autoacme.json'...OK
Checking host...OK
Requesting cerificate for example.com:
  Accepting TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf...OK
  Testing authorization:
    Writing challenge to C:\Websites\AutoACME\autoACME\probe_fec35f82-c3e1-4d74-90ad-60fa3ad87357...OK
    Testing HTTP challenge:
      Preparing request to http://example.com/.well-known/acme-challenge/probe_fec35f82-c3e1-4d74-90ad-60fa3ad87357...OK
      Getting response...OK
      Reading response...OK
        OK: Status code 200
        OK: Content-Type header
        OK: Expected response received
    Deleting challenge from C:\Websites\AutoACME\autoACME\probe_fec35f82-c3e1-4d74-90ad-60fa3ad87357...OK
  Getting authorization:
    Creating authorization request...OK, the following is request URI:
    https://acme-v01.api.letsencrypt.org/acme/authz/qtW814qPGbfyWnSB5-S3A3xafPRX_JBkM57nzky7KW0
    Getting challenge...OK, the following is challenge URI:
    https://acme-v01.api.letsencrypt.org/acme/challenge/qtW814qPGbfyWnSB5-S3A3xafPRX_JBkM57nzky7KW0/7897219451
    Writing challenge to C:\Websites\AutoACME\autoACME\FY_TrYtokAhf1kfzasVpiSA6N1yd6yDyYrceGkqRGow...OK
    Completing challenge...OK
    Waiting for authorization...OK
    Deleting challenge from C:\Websites\AutoACME\autoACME\FY_TrYtokAhf1kfzasVpiSA6N1yd6yDyYrceGkqRGow...OK
  Processing certificate:
    Requesting certificate...Request failed: One or more errors occurred.

    System.AggregateException: One or more errors occurred. ---> System.Exception: urn:acme:error:rateLimited: Error creating new cert :: too many certificates already issued for exact set of domains: example.com: see https://letsencrypt.org/docs/rate-limits/ (429)
   at Certes.AcmeClient.ThrowIfError[T](AcmeResponse`1 response)
   at Certes.AcmeClient.<NewCertificate>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certes.AcmeClient.<NewCertificate>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Altairis.AutoAcme.Core.AcmeContext.<GetCertificateAsync>d__14.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Altairis.AutoAcme.Core.AcmeContext.GetCertificate(String hostName, String pfxPassword, Action`2 challengeCallback, Action`1 cleanupCallback, Boolean skipTest)
   at Altairis.AutoAcme.Manager.Program.AddHost(String hostName, Boolean skipTest, String cfgFileName, Boolean verbose)
---> (Inner Exception #0) System.Exception: urn:acme:error:rateLimited: Error creating new cert :: too many certificates already issued for exact set of domains: example.com: see https://letsencrypt.org/docs/rate-limits/ (429)
   at Certes.AcmeClient.ThrowIfError[T](AcmeResponse`1 response)
   at Certes.AcmeClient.<NewCertificate>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certes.AcmeClient.<NewCertificate>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Altairis.AutoAcme.Core.AcmeContext.<GetCertificateAsync>d__14.MoveNext()<---

    Failed!
    Unable to get certificate for new host.
```

**Comment by matt-01** [comment]
Obviously I am not using example.com I had to redact the real domain name but it here is the problem

Error creating new cert :: too many certificates already issued for exact set of domains: example.com: see https://letsencrypt.org/docs/rate-limits/ (429)

I have 4 subdomains that currently have certificates and I need a 5th. So I should be inside the limit.

www.example.com
images.example.com
cms.example.com
example.com
cdn.example.com

**Comment by ridercz** [comment]
You hit the rate limit. Most likely not on subdomains, but you have too many certificates for `www.example.com`. You may check it on [crt.sh](https://crt.sh).

Closing, as this is not AutoACME issue.
