### ISSUE TITLE
Failed to setup

### ISSUE THREAD

**Issue by dolphinsd** [ridercz/AutoACME#39]
When following instruction, failed to setup with initcfg. Here is an error:

Checking current H:\CertStore\AutoACME\ChallengeFolder\web.config...OK
Saving H:\CertStore\AutoACME\ChallengeFolder\web.config...OK
Creating registration for 'support@mycompany.com' and accept TOS...OK

Unhandled Exception: System.AggregateException: One or more errors occurred. ---
> System.NullReferenceException: Object reference not set to an instance of an o
bject.
   at Altairis.AutoAcme.Core.AutoAcmeContext.<RegisterAndLoginAsync>d__21.MoveNe
xt()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotifica
tion)
   at System.Threading.Tasks.Task`1.get_Result()
   at Altairis.AutoAcme.Core.AutoAcmeContext.RegisterAndLogin(String email)
   at Altairis.AutoAcme.Manager.Program.InitCfg(Boolean useDefaults, String cfgF
ileName, Boolean overwrite, Boolean verbose)
   at lambda_method(Closure , Object , Object[] )
   at NConsoler.Consolery.InvokeMethod(MethodInfo method)
   at NConsoler.Consolery.RunAction()
   at NConsoler.Consolery.Run(Type targetType, String[] args, IMessenger messeng
er, Notation notationType)
   at NConsoler.Consolery.Run()
   at Altairis.AutoAcme.Manager.Program.Main(String[] args)

**Comment by ridercz** [comment]
Fixed in e64c1dc0f6b3166f55186fd7a7cdc5307df6ec5d, release 1.6.2.
